target_role_name: AutoRemediation-TargetRole
central_account: 123412341234
actions:
  - s3:CreateBucket
  - s3:DeleteBucket
  - ec2:RunInstance
management_role_name: AutoRemediationManagementRole
target_accounts:
  - 456745674567
eventbridge_role_name: AutoRemediation-EventBridge
central_event_bus_arn: arn:aws:events:eu-west-1:[account]:event-bus/[event-bus-name]