target_role_name: CyberSec-AutoRemediation-TargetRole
central_account: 458305147808
actions:
  - s3:CreateBucket
  - s3:DeleteBucket
  - ec2:RunInstance
management_role_name: AutoRemediationManagementRole
target_accounts:
  - 315958533332
eventbridge_role_name: CyberSec-AutoRemediation-EventBridge
central_event_bus_arn: arn:aws:events:eu-west-1:458305147808:event-bus/cross-account-security-alerts